### ISSUE TITLE
1 zu 3 Beziehung im Consent

### ISSUE THREAD

**Issue by biermapa** [medizininformatik-initiative/kerndatensatzmodul-consent#1]
Im Broad Consent wird jede Zustimmung zu einem Punkt durch 3 Codes dargestellt für Lagern, erheben, wissenschaftlich nutzen. Da aber jede Zustimmung im Broad Consent eine Zustimmung zu allen 3 Punkten entspricht, sehe ich eine Abbildung einer Zustimmung in 3 Punkten als redundant an. Eine 1 zu 1 Beziehung sollt ausreichen und wäre auch leichter zu interpretieren.

**Comment by JoergRoemhild** [comment]
Der Grund warum wir eine Zustimmung in 3 Codes darstellen hängt mit den unterschiedlichen Gültigkeitszeiträumen der daraus resultierenden Policy zusammen. Im Beispiel kann man das schön sehen (Medizinische Daten erheben: 5 Jahre gültig, Medizinische Daten speichern: 30 Jahre gültig, Medizinische Daten nutzen: 30 Jahre gültig.

**Comment by biermapa** [comment]
Dies ist mir durchaus bewusst, jedoch sehe ich diesen Punkt in einer nachgelagerten Interpretation in einer entsprechenden nachgelagerten (klinischen oder softwareseitigen) Anwendung und nicht innerhalb einer Consent Ressource.

**Comment by JoergRoemhild** [comment]
Wir betrachten das als festes Attribut an der Policy, was die Auswertung in der Business-Logik vereinfacht.
