### ISSUE TITLE
Patient-Profil (MII Pseud. Pat. vs. EWE Patient

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#10]
Siehe Kommentar in Simplifier [#2108](https://simplifier.net/medizininformatikinitiative-modulconsent/~issues/2108)

@mbialke und @lhitc könnt ihr euch die Antwort von DA bitte anschauen und prüfen, ob das passt bzw. ggf. den Vorschlag umsetzen?

**Comment by mbialke** [comment]
aus meiner sicht erledigt. siehe anmerkung. kein weitere rückmeldung.

**Comment by mbialke** [comment]
@SebStaeubert kann aus meiner sicht geschlossen werden, es sei denn, danny hat weitere rückmeldung.
