### ISSUE TITLE
Einheitliche Verwendung von Patient Ressourcen prüfen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#13]
Es sollte geprüft werden, ob über alle Profile des mii-spez. Moduls Consent das passende und möglichst einheitliche Profil einer Patient Ressource verwendet bzw. verwiesen wird!
Aktuell in den MII-spez. Profilen:
- Consent -> Consent Management Patient (hl7)
- Provenance.signature.who -> Patient
- DocumentReference.subject -> Consent Management Patient (hl7)

Zusätzlich prüfen, ob es zu Inkonsistenzen kommen kann, wenn Profile aus dem hl7-Einwilligungsmanagement benutzt werden, z.B. QuestionnaireResponse -> Consent Management Patient (hl7)

Die MII bzw. das KDS Modul Person kennt die folgenden:
- [SD_MII_Person_Patient](https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatient)
- [SD_MII_Person_PatientPseudonymisiert](https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatientpseudonymisiert)
Prüfen, ob diese Patienten Profile verwendet werden können.

Wir sollten diese mgl. Inkonsistenzen auflösen bzw. einen Absatz im IG schreiben, wie damit umgegangen werden soll.

**Comment by mbialke** [comment]
@lhitc Consent Management Patient (hl7) stellt im Kern eine Variante von Patient dar, die keinerlei weitere Infos außer dem/den Pseudonym(en) enthält. eine konsequente Nutzung von Consent Management Patient (hl7) auch bei Provenance.signature.who wäre sicherlich nicht verkehrt.

In Summe wäre wohl die einfachste Variante
- obenstehende Profile alle zuzulassen
- auf konsequente und einheitliche Nutzung der Profile hinzuweisen
- Nutzungsempfehlung für Consent Management Patient (hl7) zu geben
- zu prüfen ob alle obigen Varianten von Patient verwendet werden dürfen @lhitc 

In diese Richtung könnte dann auch die Validierungsmeldung gehen: "Achtung fehlende Einheitlichkeit".
Eine Frage aber bleibt: wenn es in Richtung FDPG geht sollte nach Möglichkeit nur exakt ein Profil empfohlen werden. Mein Vorschlag: Consent Management Patient (hl7)

**Comment by SebStaeubert** [comment]
Siehe [IG Consent-Ressource](https://simplifier.net/guide/MedizininformatikInitiative-ModulConsent-ImplementationGuide/IGMIIKDSModulConsent/TechnischeImplementierung/FHIRProfile/Consent.guide.md?version=current)

Absatz: "Technisch gesehen können Patienten-Ressourcen, die zu den Profilen der [AG Einwilligungsmanagement](https://ig.fhir.de/einwilligungsmanagement/stable/Patient.html) und der [MII](https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatientpseudonymisiert) konform sind, verwendet werden." um ein Beispiel unter Verwendung Modul Person [SD_MII_Person_Patient](https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatient) und 
[SD_MII_Person_PatientPseudonymisiert](https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatientpseudonymisiert) ergänzen. Beschreiben, dass Patient und abgeleitete Profile verwendet werden, solange sie eine patient.identifier.type besitzen.

**Comment by mosaic-hgw** [comment]
Prosa Text ist angepasst. Bitte @lhitc Beispiele ergänzen siehe Todo im IG Text

**Comment by mosaic-hgw** [comment]
Habe zusätzlich noch einen Nebensatz zur Verwendung von IDAT in "pseudonymen Patienten" ergänzt. @SebStaeubert

**Comment by mosaic-hgw** [comment]
"Etwaige personenidentifizierende Informationen (z.B. Geburtsdatum, Geschlecht,Anschrift) sowie Referenzen, z.B. auf (Klartext-) Patienten-Profile, sollten vor Ausleitung geeignet ersetzt werden."

**Comment by lhitc** [comment]
Ich wüsste gerade nicht, wie ich die beiden Beispiele differenzieren sollte.
Aus Sicht der Consent-Ressource ist beides eines Reference(Patient), und die Patient-Instanzen selbst wären völlig identisch.

Ich denke, hier reicht der von Martin verfasste Absatz völlig aus.

Ping @SebStaeubert @mbialke

**Comment by mosaic-hgw** [comment]
Mein Okay hast du.

**Comment by lhitc** [comment]
Dann bin ich mal so frei und nehme die TODOs raus, lasse das Issue aber noch offen

**Comment by mosaic-hgw** [comment]
Danke! So machen wir (du) es :)
