### ISSUE TITLE
Consent.dateTime: Beschreibung und Definition anpassen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#2]
Aktuell steht in Beschreibung und Definition unter 'Consent.dateTime' folgendes:

> Short description
> Gültigkeitsbeginn der Einwilligung
> 
> Definition
> Ab diesem Zeitpunkt gilt die hier dokumentierte Einwilligungserklärung

Laut FHIR Standard beschreibt dieses Attribut jedoch:

> Definition | When this Consent was issued / created / indexed.
> Comments | This is not the time of the original consent, but the time that this statement was made or derived.

**Comment by SebStaeubert** [comment]
Beispiel und anschauliche Darstellung könnte helfen, z.B. 
![image](https://user-images.githubusercontent.com/11329281/161266312-401157c6-93fb-4e91-b273-a77468862aa2.png)

**Comment by SebStaeubert** [comment]
Update
![image](https://user-images.githubusercontent.com/11329281/165914664-1c88094e-8aaf-411d-906c-7d757647fb50.png)

**Comment by SebStaeubert** [comment]
Bzw. Darstellung (J. Mang)
[MIIC-197798769-180322-0938-312.pdf](https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/files/8589584/MIIC-197798769-180322-0938-312.pdf)

**Comment by SebStaeubert** [comment]
[Ticket im Github-Repo der AG EWE](https://github.com/hl7germany/einwilligungsmanagement/issues/26) angelegt.

**Comment by SebStaeubert** [comment]
Update
![image](https://user-images.githubusercontent.com/11329281/172357971-9abc4b14-0ceb-486a-adfe-cc08a84bae3a.png)

**Comment by lhitc** [comment]
wartet auf #11

**Comment by lhitc** [comment]
erledigt

**Comment by SebStaeubert** [comment]
@lhitc müsste das nicht noch in den IG?
[https://simplifier.net/guide/MedizininformatikInitiative-ModulConsent-ImplementationGuide/IGMIIKDSModulConsent/TechnischeImplementierung/FHIRProfile/Consent.guide.md?version=current](https://simplifier.net/guide/MedizininformatikInitiative-ModulConsent-ImplementationGuide/IGMIIKDSModulConsent/TechnischeImplementierung/FHIRProfile/Consent.guide.md?version=current)

**Comment by lhitc** [comment]
@SebStaeubert War bisher auch nicht drin und ist ja dann sowohl im Rendering des Consent-Profils korrekt sichtbar als auch im referenzierten Einwilligungsmanagement-IG. Von daher würde ich sagen, das kann so bleiben,

**Comment by SebStaeubert** [comment]
@lhitc Wenn man mit der Maus über dateTime (unter "Darstellung") geht und den Text liest, ist dieser noch falsch. Evtl. aktualisiert sich das noch?

**Comment by lhitc** [comment]
@SebStaeubert Genau; das hat Simplifier schlicht noch nicht mitbekommen und ich re-importiere dann zum Schluss die Profile ohnehin nochmal nach Simplifier, so dass der Snapshot-Generator dann den neuen Text aus Einwilligungsmanagement übernimmt.
