### ISSUE TITLE
Hinweis auf Finale Version in der Arbeitsversion ergänzen

### ISSUE THREAD

**Issue by violaBe** [medizininformatik-initiative/kerndatensatzmodul-consent#28]
Im draft https://simplifier.net/guide/medizininformatikinitiative-modulconsent-implementationguide?version=current fehlt Link zum aktuellen release. bitte ergänzen.

**Comment by SebStaeubert** [comment]
Danke für den Hinweis. Der Link wurde hinzugefügt.
