### ISSUE TITLE
Hierachy Meaning cannot be is-a

### ISSUE THREAD

**Issue by geloro94** [medizininformatik-initiative/kerndatensatzmodul-consent#29]
The CodeSystem for policies defines the hierarchyMeaning as an is-a relationship:
  <hierarchyMeaning value="is-a"/>
  
Based on the FHIR definition for is-a:
> A hierarchy where the child concepts have an IS-A relationship with the parents - that is, all the properties of the parent are also true for its child concepts. Not that is-a is a property of the concepts, so additional subsumption relationships may be defined using properties or the [subsumes](extension-codesystem-subsumes.html) extension.

This does not work for the given use case: 
Let's say we have the concepts A, B, and C. A and B are in an is-a relationship with C. A patient has the concept C iff the patient has the concept A AND B. 
The IS-A relationship implies a direct inheritance, meaning everything that's true for Concept C is true for Concept A (and Concept B). If Concept A on its own doesn't fulfill all the characteristics of Concept C (The patient has Concept A and B), then it's inaccurate to say that Concept A has an IS-A relationship with Concept C.

Applied to the given context: A patient only agrees to the parent consent if he agrees to all its subparts.

The defined part-of relationship might be more suitable:
Child elements list the individual parts of a composite whole (e.g. body site).

**Comment by geloro94** [comment]
Der Punkt wäre die Bitte um die Anpassung des CodeSystems in der Verwendung der Relation von is-a zu part-of. Allgemein ist hier mit Concept ein codiertes Concept aus einem CodeSystem gemeint. Für den Kokretenfall bezieht es sich auf Policiies.

**Comment by SebStaeubert** [comment]
@geloro94 Es geht also um diese Angabe im CodeSystem:
`<hierarchyMeaning value="is-a"/>`

@lhitc , @mbialke : Spricht etwas dagegen? Weiß jemand, ob dazu etwas in ART-DECOR angepasst werden muss oder wird das hierarchyMeaning erst als "Nachbearbeitung" erzeugt?

**Comment by mosaic-hgw** [comment]
Aktiv erzeugt wurde es meiner Kenntnis nach von uns nicht. Ein Automatismus? @lhitc

**Comment by lhitc** [comment]
part-of ist in jedem Fall hier korrekt.
Wir müssen hier nur prüfen, ob das "is-a" bereits aus ART-DECOR kommt (dann muss es dort korrigiert werden) oder ob mir ggf. beim Bereinigen ein Copy&Paste-Fehler unterlaufen ist, dann wäre schlicht die Ressource zu ändern.

**Comment by SebStaeubert** [comment]
Der ART-DECOR Export von CodeSystemen ist aktuell gestört (Ticket für AD-Entwickler ist geschrieben). Die Änderungen sind daher direkt im Code in diesem github erfolgt. Es sind keine Änderungen im AD erfolgt, d.h. der Fehler tritt evtl. bei einem erneuten Export wieder auf.
