### ISSUE TITLE
Beispiel zur Verwendung von Consent.provision.period.start/end bzw. Consent.provision.provision.period.start

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#3]
Der MII BC gilt für Behandlungsfälle, die eine Überlappung des Gültigkeitszeitraumes haben.
Es sollte ein aussagekräftiges Beispiel geben, z.B. anhand eines Zeitstrahls: Datum Patient kommt ins KH, Patient erhält erste Diagnostik, Patient gibt Consent, usw.

Davon unbenommen ist das Modul 'Retrospektive Datennutzung'.

**Comment by SebStaeubert** [comment]
ToDos:
- Artifizielles Beispiel / Story entwerfen* -> @JoergRoemhild, @SebStaeubert 
- Beispielhafte Auswertung entwerfen* (ggf. Verweis auf eine noch erarbeitende Doku zur Durchführung, z.B. [Fallbezug](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Fall/IGMIIKDSModulFall.html)) -> @JoergRoemhild 
- technische Umsetzung mit Beispiel-Queries erstellen -> @lhitc 
- Disclaimer: Nicht allgemein gültig! Nur Beispiel!

- Einbettung in den IG, ggf. neue Überschrift anlegen bzw. Vorgaben an die Struktur des IG beachten -> @lhitc 

* sinnvolle Annahmen treffen

**Comment by SebStaeubert** [comment]
ref. 1.: [github-wiki/Example-Scenario-MDAT---Consent-based-Access-Control](https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/wiki/Example-Scenario-MDAT---Consent-based-Access-Control)

**Comment by SebStaeubert** [comment]
Die Prüfung des Consents bei der Herausgabe/Verwendung von MDAT muss durch eine Software erfolgen. Die Funktionsbeschreibung dieser Software (vgl. Policy Decision Point, Sicherheitskonzept) ist nicht Gegenstand der Profilierung. Die TF Consent Umsetzung kümmert sich nach Abschluss der Profilierung um eine Beschreibung/Spezifikation für den Anwendungsfall: Ermittle auf Basis des Consents zulässige Pseudonyme, für die angefragten MDAT (inkl. Zeiträume).

**Comment by lhitc** [comment]
Mit SearchParameter bereits erledigt
