### ISSUE TITLE
Modul Consent auf MII Naming Conventions prüfen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#4]
Die [Naming Conventions des MII KDS](https://tmfev.sharepoint.com/:w:/r/sites/tmf/mi-i/Taskforce%20Terminologiedienste/02_Dokumente/Naming%20Conventions%20f%C3%BCr%20die%20Erstellung%20von%20FHIR%20Terminology%20Resources%20in%20der%20MII.docx?d=wde61644d09a64450baa5d58b80221609&csf=1&web=1&e=OWKDaI) stehen kurz vor einem Beschluss. Wir sollten prüfen, ob das Modul Consent bereits konform ist und ggf. anpassen, wenn es nicht zu gravierenden Problemen führt.

**Comment by SebStaeubert** [comment]
[20220504_Naming Conventions für die Erstellung von FHIR Terminology Resources in der MII.pdf](https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/files/8830864/20220504_Naming.Conventions.fur.die.Erstellung.von.FHIR.Terminology.Resources.in.der.MII.pdf)

**Comment by SebStaeubert** [comment]
Dokument ist noch in Kommentierung und es sind bereits Kommentare eingegangen. Ggf. wird das hier verlinkte Dokument noch einmal aktualisiert.

**Comment by lhitc** [comment]
finales Dokument bitte hier verlinken

**Comment by SebStaeubert** [comment]
Update: Diskussion läuft noch. Das Dok. geht nun noch einmal in eine Taskforce... 
Für die aktuelle MII-spez. Ballotierung sollte dieses Ticket kein Blocker sein. D.h. muss für die jetzige Ballotierungsrunde nur berücksichtigt werden, falls das Dok. rechtzeitig vorliegt. Wenn nicht wird es in der nächsten Runde berücksichtigt.

**Comment by alexzautke** [comment]
Bei der Vergabe der Canonicals sollte vielleicht bereits auf die Naming Convention geachtet werden, sodass diese nicht nachträglich geändert werden müssen.

**Comment by SebStaeubert** [comment]
Update (aber noch nicht final): [20220829_Naming Conventions für die Erstellung von FHIR Terminology Resources in der MII.pdf](https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/files/9488644/20220829_Naming.Conventions.fur.die.Erstellung.von.FHIR.Terminology.Resources.in.der.MII.pdf)

**Comment by SebStaeubert** [comment]
Finale Version:
[Namenskonventionen für die Erstellung von FHIR-Ressourcen in der MII.pdf](https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/files/9681322/Namenskonventionen.fur.die.Erstellung.von.FHIR-Ressourcen.in.der.MII.pdf)

**Comment by SebStaeubert** [comment]
- [ ] Canonicals anpassen

**Comment by lhitc** [comment]
Auch names angepasst, um ein Minimum an Konsistenz innerhalb der Ressourcen herzustellen.
Ebenso IG überarbeitet (broken Links und veraletete Angaben infolge neuer Canonicals / Names)
