### ISSUE TITLE
Consent Fallbezug

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#47]
Für das Enforcement gibt es die Anforderung, dass der Fallbeginn des Falls berücksichtigt wird, in dessen "Zusammenhang" bzw. Zeitraum der Consent erfasst wurde.
Der Bezug Consent mit diesem Fall kann über eine zeitliche Überschneidung z.B. mittels Abfragelogik erfolgen (Variante a).
Oder über eine Referenz angegeben werden, z.B. in Provenance.target (Variante b).

Für Variante b müsste die Provenance-Ressource entspr. profiliert werden.

Meinungen?

**Comment by oeme-github** [comment]
Ich denke das der zeitliche Bezug einfacher ist, sofern der Fall die entsprechende Information enthält. Mir ist nicht ganz klar wie das über die Provenance funktionieren soll. Ist das dann eine 1:1 Beziehung auf einen spezifischen Fall? Was ist dann wenn es in dem Zeitraum mehr als eine Fall gibt? Kann das vorkommen? 
Nach meinem Verständnis führt der zeitliche Bezug zu einem oder mehrere Fällen zu einem einheitlichen Verhalten, die Daten zu den Fällen sind immer inkludiert. Das wirft aber die Frage auf ob die Daten auch immer einen Fallbezug haben und wenn nein ob dann der ältere Fall als Startpunkt genommen werden kann.

**Comment by SebStaeubert** [comment]
Ich denke auch, dass Variante a) einfacher umzusetzen ist. Siehe https://github.com/medizininformatik-initiative/torch/issues/6
