### ISSUE TITLE
acribis Policies in Policy ValueSet anlegen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#54]
Nach Einschätzung der TF CU ist das verfügbare KDS Modul Consent geeignet, die Acribis Policies abzubilden. Es ist jedoch eine Erweiterung des Policy Value Sets erforderlich.
Die TF CU schlägt die folgenden Policies vor. "l-1"/"l-2" sind Ebenen im Value Set, wobei "l-1" per Konvention mit einer Frage im Consent-Formular korrespondiert und "l-2" die eigentliche Policy zur technischen Verwendung (Enforcement) enthält. In Klammern haben wir die Laufzeit angegeben, welche im Beschreibungstext der Policy hinterlegt wird. Außerdem gibt es zu einigen Policies Rückfragen (ebenfalls in Klammern):

1. l-1 Z2_PATDAT_erheben_nutzen_kontakt_acribis
2.   l-2 MDAT_erheben_acribis
      (Gültigkeit: 5 Jahre)
3.   l-2 MDAT_speichern_verarbeiten_wissenschaftlich_nutzen_acribis
      (Ggf. Hinweis auf Verarbeitung auf "EU_DSGVO_NIVEAU"? Ist die Zusammenführung mit Dritten geplant?)
4.   l-2 Rekontaktierung_Followup_Email_acribis
5. l-1 Z2_IDAT_Melderegister_abfragen_speichern_verarbeiten_acribis
6.   l-2 IDAT_Melderegister_abfragen_speichern_verarbeiten_acribis
      (Wir gehen davon aus, dass es für die Aufgaben einheitliche Fristen gibt, z.B. 5 Jahre, richtig?)
7. l-1 Z2_MDAT_Hausarzt_erheben_speichern_verarbeiten_nutzen_acribis
8.   l-2 MDAT_Hausarzt_erheben_Schweigepflicht_entbinden_acribis
      (5 oder 30 Jahre gültig?)
9.   l-2 MDAT_Hausarzt_speichern_verarbeiten_wissenschaftlich_nutzen_acribis
      (30 Jahre gültig?)

Bitte geben Sie uns eine Rückmeldung, ob Sie bzw. Acribis mit dem Vorschlag einverstanden ist oder ob Sie noch Änderungsbedarf sehen.
Nach der Rückmeldung können wir mit der Umsetzung, d.h. dem Anlegen und Publikation der Polices (ART-DECOR, etc.) starten.

- [x] Rückmeldung Acribis
- [x] acribis Policies in Policy ValueSet anlegen
   - [x] ART-Decor
   - [ ] simplifier
   - [ ] IG

**Comment by SebStaeubert** [comment]
### Stand / Vorschlag 06.12.2024
1. (l-1) Z2_PATDAT_erheben_nutzen_kontakt_acribis
2.   (l-2) PATDAT_erheben_nutzen_kontakt_acribis
5. (l-1) Z2_IDAT_Melderegister_abfragen_speichern_verarbeiten_acribis
6.   (l-2) IDAT_Melderegister_abfragen_speichern_verarbeiten_acribis
7. (l-1) Z2_MDAT_Hausarzt_erheben_speichern_verarbeiten_nutzen_acribis
8.   (l-2) MDAT_Hausarzt_erheben_speichern_verarbeiten_nutzen_acribis

Gültigkeitszeiträume?
- Keine! Wird acribis-Projekt intern abgestimmt.

**Comment by mbialke** [comment]
ergibt sich auf dem mii bc selbst: 30y

**Comment by SebStaeubert** [comment]
- [ ] Acribis AD DataSet anlegen
- [ ] Answer VS zuweisen
- [ ] CS um ACRIBIS Policies ergänzen
- [ ] OIDs eintragen in [TFCU-PolicyAbbildung_v12_MII_BC](https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/Taskforce%20Consent%20Umsetzung/02_Dokumente/Policies/TFCU-PolicyAbbildung_v12_MII_BC.xlsx?d=wab91b4e1a8a6402d88ba8e30c857df36&csf=1&web=1&e=0kuyHO)
