### ISSUE TITLE
Prüfung Policies Zusatzmodul Patientenbefragung (PROM, EyeMatics)

### ISSUE THREAD

**Issue by mbialke** [medizininformatik-initiative/kerndatensatzmodul-consent#56]
Mein Vorschlag für das nun allgemeine PROM Modul anbei und zur Diskussion nachher.

Dokuemnt: https://tmfev.sharepoint.com/:b:/r/sites/tmf/mi-i/Taskforce Consent Umsetzung/02_Dokumente/MII Consent Mustertexte/[Zusatzmodul Patientenbefragung (ehemals EyeMatics) v2.pdf](https://tmfev.sharepoint.com/:b:/r/sites/tmf/mi-i/Taskforce%20Consent%20Umsetzung/02_Dokumente/MII%20Consent%20Mustertexte/Zusatzmodul%20Patientenbefragung%20(ehemals%20EyeMatics)%20v2.pdf?csf=1&web=1&e=aZ2B0Q)?csf=1&web=1&e=aZ2B0Q

Erläuterung
-	PROM sehe ich als Untermenge von MDAT. Daher mein Vorschlag MDAT_PROM
-	Ich gehe davon aus, dass auch hier nur 5y erhoben werden darf
-	Ein Eyematics-suffix ist aufgrund der Verallgemeinerungen nicht mehr erforderlich.

Modul Patientenbefragung PROM
-	Policy MDAT_PROM_erheben (läuft ab nach 5 Jahren)
-	Policy MDAT_PROM_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU (keine Einschränkung Laufzeit)
-	Policy Rekontaktierung_PROM_Studien (keine Einschränkung Laufzeit)

Offene Frage: braucht es eine neue Mustertext-Version die das Modul beinhaltet, z.b. 1.7.3? Aktuell wäre das Modul irgendwie in der Luft.

**Comment by mbialke** [comment]
Modul Patientenbefragung PROM
•	Policy PROMDAT_erheben (läuft ab nach 5 Jahren)
•	Policy PROMDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU (keine Einschränkung Laufzeit)
•	Policy Rekontaktierung_PROM_Studien (keine Einschränkung Laufzeit)

**Comment by mbialke** [comment]
Die AG Consent müsste vorgeben, mit welchen "Basis" BC (1.6b, 1.7.2) dieses Zusatzmodul kombiniert werden darf oder ob es Bestandteil einer neuen Version ist.

**Comment by SebStaeubert** [comment]
Stand 11.12.2024, siehe [Tabelle SharePoint](https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7BAB91B4E1-A8A6-402D-88BA-8E30C857DF36%7D&file=TFCU-PolicyAbbildung_v12_MII_BC.xlsx&action=default&mobileredirect=true)
Modul "Z3_PROMDAT_Patientenbefragung"
•	Policy PROMDAT_erheben (läuft ab nach 5 Jahren)
•	Policy PROMDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU (keine Einschränkung Laufzeit)
•	Policy Rekontaktierung_PROM_Studien (keine Einschränkung Laufzeit)

- [ ] Policies inkl. OIDs in Tabelle und ART-Decor eintragen

**Comment by SebStaeubert** [comment]
- [ x ] [PROM AD DataSet](https://art-decor.org/art-decor/decor-datasets--mide-?id=2.16.840.1.113883.3.1937.777.24.1.1&effectiveDate=2018-06-05T12%3A44%3A12&conceptId=2.16.840.1.113883.3.1937.777.24.2.4036&conceptEffectiveDate=2024-12-13T11%3A04%3A09&language=de-DE) anlegen
- [ x ] Answer VS zuweisen
- [ x ] CS um PROM Policies ergänzen
- [ x ] OIDs eintragen in [TFCU-PolicyAbbildung_v12_MII_BC](https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/Taskforce%20Consent%20Umsetzung/02_Dokumente/Policies/TFCU-PolicyAbbildung_v12_MII_BC.xlsx?d=wab91b4e1a8a6402d88ba8e30c857df36&csf=1&web=1&e=0kuyHO)
