### ISSUE TITLE
Mehr Flexibilität und Justierung der Kardinalitäten Consent.category und Consent.provision

### ISSUE THREAD

**Issue by mbialke** [medizininformatik-initiative/kerndatensatzmodul-consent#57]
Mehr Flexibiliät ermöglichen 

- [x] 1. Consent.category -> max value="*"
- [x] 2- Consent.provision.type ->fixedCode deny entfernt
- [x] 3. Consent.provision.provision.type ->fixedCode permit entfernt

Details zu Bedingungen von 2. und 3. in abhängigkeit zu optin/optout folgen. muss noch ausspezifiziert werden.

**Comment by mbialke** [comment]
der letzte punkt wird in der HL7D aG Einwilligungsmanagement gelöst siehe https://github.com/hl7germany/einwilligungsmanagement/issues/63

**Comment by mbialke** [comment]
solved https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/commit/c3a0c9c5c10d82187a2afa9d2bb0555c023f1388

**Comment by SebStaeubert** [comment]
IG Erklärungen noch angepasst:

> Consent.provision.type|value ```DENY``` oder ```PERMIT```, Must-support

bzw.

> Consent.provision.provision.type|value ```PERMIT``` oder ```DENY```, Must-support
