### ISSUE TITLE
SMITH Rückmeldungen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#6]
Wozu wird das Patientenprofil genutzt?

- Ist Patient.identifier.type in dem Profil verpflichtend?
- Sollte besser das Profile des pseudonymisierten Patienten genutzt werden? → in SMITH gibt es die "Research Domain" in der consentierte und pseudonymisierte MDAT gehalten werden. Dort soll auf eine pseud. Pat. Ress. verwiesen werden (Consent.patient). Evtl. ein passendes Beispiel in den IG einfügen

**Comment by SebStaeubert** [comment]
> * Sollte besser das Profile des pseudonymisierten Patienten genutzt werden? → in SMITH gibt es die "Research Domain" in der consentierte und pseudonymisierte MDAT gehalten werden. Dort soll auf eine pseud. Pat. Ress. verwiesen werden (Consent.patient). Evtl. ein passendes Beispiel in den IG einfügen

Ja, siehe [Beschreibung der FHIR Consent Ressource im IG](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Consent/Consent.html), insbesondere findet sich eine Erläuterung dazu im Abschnitt "Datenschutz-Aspekte". Hier wird auf die bereits in [der HL7-Ballotierung profilierte Patient Ressource (inkl. Beispiel)](https://ig.fhir.de/einwilligungsmanagement/stable/Patient.html) verwiesen.
Der [Abschnitt "Datenschutz-Aspekte"](https://simplifier.net/guide/MedizininformatikInitiative-ModulConsent-ImplementationGuide/IGMIIKDSModulConsent/TechnischeImplementierung/FHIRProfile/Consent.guide.md?version=current) wurde überarbeitet und der Verweis auf die Patient Ressource (HL7-Ballotierung) verwiesen.

> * Ist Patient.identifier.type in dem Profil verpflichtend?

Ja, ist verpflichtend, um den Typ des Identifiers ([entsprechendes ValueSet](https://ig.fhir.de/einwilligungsmanagement/stable/ContextIdentifierType.html)) zu beschreiben.

**Comment by mbialke** [comment]
@SebStaeubert gab es feedback oder kann das ticket geschlossen werden?

**Comment by SebStaeubert** [comment]
Ich habe nach der Sommerpause noch einmal eine Frist bis 14.09.2022 gegeben, dann tagt die entspr. Runde in SMITH.

**Comment by SebStaeubert** [comment]
- [ ] Link an Profil anpassen

**Comment by lhitc** [comment]
Anpassung ist nicht erforderlich: die Reference verweist auf den Patient aus IG AG EWE (vulgo: "Consent Management"), im IG MII Consent haben wir kein eigenes Patient Profil.
Somit ist bereits alles konsistent.
